USE [master]
GO

/****** Object:  Database [NawazEyeWebsiteProject]    Script Date: 5/30/2018 6:45:47 PM ******/
CREATE DATABASE [NawazEyeWebsiteProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NawazEyeWebsiteProject', FILENAME = N'D:\Program Files\MSSQL\server instance\MSSQL14.MYSQLINSTANCE\MSSQL\DATA\NawazEyeWebsiteProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NawazEyeWebsiteProject_log', FILENAME = N'D:\Program Files\MSSQL\server instance\MSSQL14.MYSQLINSTANCE\MSSQL\DATA\NawazEyeWebsiteProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NawazEyeWebsiteProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET  MULTI_USER 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET QUERY_STORE = OFF
GO

USE [NawazEyeWebsiteProject]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [NawazEyeWebsiteProject] SET  READ_WRITE 
GO

